name: ASP.NET CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore -c Release

    - name: Test api project
      run: dotnet test --no-build -c Release --verbosity normal

    - name: Global instruments
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Run pipe for project
      run: dotnet build /p:RunCodeAnalysis=true